spring.application.name=minimarket
# Nombre de la aplicación

# Configuración del servidor
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pedido?currentSchema=market&serverTimezone=America/Lima
 spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Mostrar las consultas SQL en consola (útil para depuración)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true